INSERT INTO DEVELOPER VALUES(1, 'Vipul', 'JAVA');
INSERT INTO DEVELOPER VALUES(2, 'Rakesh', 'DOTNET');
INSERT INTO DEVELOPER VALUES(3, 'Ankush', 'VisualBasic');
INSERT INTO DEVELOPER VALUES(4, 'Abhinash', 'ANDROID');
